### ISSUE TITLE
Add No such file or directory in cd

### ISSUE THREAD

**Issue by Bortize** [Bortize/42_minishell#35]
when the tree in which the directory is located is deleted

**Comment by Bortize** [comment]
A problem has been detected with the function "search_in_list.c". 

When receiving a pointer to null, when using ft_strlen inside ft_strdup, it explodes.


==18574==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000108882890 bp 0x7ffee73a0570 sp 0x7ffee73a0570 T0)
==18574==The signal is caused by a READ memory access.
==18574==Hint: address points to the zero page.
    #0 0x10888288f in ft_strlen (minishell:x86_64+0x10002388f)
    #1 0x10888274e in ft_strdup (minishell:x86_64+0x10002374e)
    #2 0x10888975e in set_key_value search_in_list.c:60
    #3 0x108888901 in builtins_cd builtins_cd.c:64
    #4 0x108885ce6 in run_single_builtin run_single_builtin.c:40
    #5 0x108885af1 in start_execution start_execution.c:37
    #6 0x1088831d9 in main minishell.c:122
    #7 0x7fff69cfd3d4 in start (libdyld.dylib:x86_64+0x163d4)

==18574==Register values:
rax = 0xffffffffffffffff  rbx = 0x00007ffee73a05e0  rcx = 0x0000000000000102  rdx = 0x0000000000000103
rdi = 0x0000000000000000  rsi = 0x000000010a1710e0  rbp = 0x00007ffee73a0570  rsp = 0x00007ffee73a0570
 r8 = 0x0000000000000018   r9 = 0x00000fffffffffff  r10 = 0x0000000000000000  r11 = 0xffffffffffffffff
r12 = 0x00001c040000016f  r13 = 0x00001fffdce740b4  r14 = 0x0000000000000000  r15 = 0x0000602000000b78
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (minishell:x86_64+0x10002388f) in ft_strlen
==18574==ABORTING
[1]    18574 abort      ./minishell

**Comment by Bortize** [comment]
FIXED✅ , but I leave it open for @Vicest  to review and approve it
